# Generated by Django 4.0 on 2021-12-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('word', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('difficulty', models.PositiveSmallIntegerField(unique=True)),
                ('translation', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['difficulty'],
            },
        ),
    ]
